### ISSUE TITLE
Offer builder function for parser

### ISSUE THREAD

**Issue by bsaul** [freckle/blammo#20]
Would y'all consider a builder function for `parser` for  [`Blammo.Logging.LogSettings.Env`](https://hackage.haskell.org/package/Blammo-1.0.2.3/docs/Blammo-Logging-LogSettings-Env.html)? 
As in something like:

```haskell
makeParser :: 
    LogSettings -- ^ default 
   -> Parser Error LogSettings
makeParser settings = ($ settings) . appEndo . mconcat <$> sequenceA
  [ var (endo readLogLevels setLogSettingsLevels) "LOG_LEVEL" (def mempty)
  , var (endo readLogDestination setLogSettingsDestination) "LOG_DESTINATION" (def mempty)
  , var (endo readLogFormat setLogSettingsFormat) "LOG_FORMAT" (def mempty)
  , var (endo readLogColor setLogSettingsColor) "LOG_COLOR" (def mempty)
  ]

parser :: Parser Error LogSettings
parser = makeParser defaultLogSettings
```

The default for many of our applications is to output logs to `stderr`, and it would be nice to be able to set the defaults for the parser.

Happy to open an MR if this is of interest.

Thanks for the package, btw, it's great.

**Comment by pbrisbin** [comment]
Hi, glad you like the package! Your suggestion sounds good, I would suggest we give that module the following interface:

```hs
parse :: IO LogSettings
parse = parseWith defaultLogSettings

parser :: Parser Error LogSettings
parser = parserWith defaultLogSettings

parseWith :: LogSettings -> IO LogSettings
parseWith = undefined

parserWith :: LogSettings -> Parser Error LogSettings
parserWith = undefined
```

WDYT?

**Comment by bsaul** [comment]
That interface looks good to me.

**Comment by pbrisbin** [comment]
@bsaul would you like to PR this, or should I add it to my own TODOs?

**Comment by bsaul** [comment]
@pbrisbin - I will try to put up a PR this week.

**Comment by pbrisbin** [comment]
We ended up needing this in our own project just now, so I went ahead with it. Please see the referenced PR above.

**Comment by bsaul** [comment]
Oh great! Sorry I didn't get to it -- in the last couple of weeks at work and tying up a lot of loose ends.

**Comment by pbrisbin** [comment]
No worries at all, thanks for raising the Issue!
