### ISSUE TITLE
Extract Blammo-wai

### ISSUE THREAD

**Issue by pbrisbin** [freckle/blammo#36]
The main `Blammo` library contains a WAI middleware for logging. This should be in a separate `Blammo-wai` package, so that non-web usages (e.g. CLIs) don't need to incur the dependency on `http-types` or `wai`.

I assume this will mean making this repository multi-package (rather than making a separate repository, though I'm open to that too). If going multi-package, the `freckle/bcp47` repo can be used as a model.

**Comment by chris-martin** [comment]
Done in #49
