### ISSUE TITLE
Delay in flushLogStr introduces unwanted pauses

### ISSUE THREAD

**Issue by chris-martin** [freckle/blammo#41]
`runLoggerLoggingT` flushes at the end of the action. As of Blammo-1.1.2.3, this means that it incurs a 0.1-second thread delay. This means that, for example, if you have an app setup that looks like this:

```haskell
loadApp f = checkpointCallStack $ do
  appSettings@AppSettings {..} <- loadAppSettings
  initialFaktorySettings <- Faktory.envSettings
  appLogger <- newLogger appLogSettings
  appAwsEnv <- runLoggerLoggingT appLogger AWS.envDiscover
  appSqlPool <- runLoggerLoggingT appLogger makePostgresPool
  _...
```

... This seems like a reasonable thing to write, but it incurs 0.2 seconds of unnecessary pausing. It seems that `runLoggerLoggingT` carries the unstated assumption that it will only be run once, at the outermost layer of an application, and this does not seem to hold true in the wild. Blammo-1.1.2.3 would be an unacceptable performance regression for us and probably for others, and I think we ought to deprecate it.

cc @pbrisbin

**Comment by pbrisbin** [comment]
> it incurs 0.2 seconds of unnecessary pausing

I'd quibble with "unnecessary" here. The bug in fast-logger that causes flushes to not flush (and so error logs to potentially be lost) and so this pausing being our workaround makes it at least a bit "necessary", IMO.

> unstated assumption that it will only be run once, at the outermost layer of an application

Indeed.

> and this does not seem to hold true in the wild

Can you say more about when it's not true? I think you bumped into this in tests, where each `it` corresponds to a `loadApp` call, but I want to be explicit.

All that said, `fast-logger` has been fixed now, so we just need to confirm it's been released, add a bound, and release a new version of Blammo.

> we ought to deprecate it.

Once a release is out on a fixed fast-logger, I'm fine with this.

**Comment by chris-martin** [comment]
Specifically I ran into this where a test was calling `Freckle.Jobs.Enqueue.enqueueJobs` with 19 `ProduceProficiencyEventJob`s.

The issue may be this instance:

```haskell
instance (Yesod site, HasLogger site) => MonadLogger (YesodExample site) where
  monadLoggerLog loc source level msg = do
    site <- getTestYesod
    runLoggerLoggingT site $ monadLoggerLog loc source level msg
```

I think this causes a flush after every log message?

**Comment by pbrisbin** [comment]
Sure does.

That's a bad pattern generally, that I think we do want users to avoid. `runLoggerLoggingT` is conceptually an acquire-cleanup function that just happens to not do as much cleanup as it really should (i.e. cleaning up log file handles) which make it _possible_ to use like this, until the flush delay exposed the situation for what it is.

I think I'd like to at least be free to make this function do whatever cleanup it should, but we'll need to expose a bit more from this library so that user can makes such instances. I'm just not totally sure what that should look like yet.

**Comment by pbrisbin** [comment]
I guess I'm open to the "let's just not" argument. We can keep such usage safe once we remove the delay in flush. The file handles are really the only resource I can think of that we "should" clean up, and that risk we incur by not doing so is small.
