### ISSUE TITLE
Allow a "null" log destination

### ISSUE THREAD

**Issue by neongreen-sc** [freckle/blammo#50]
Currently it's unclear how to silence the logs entirely. Setting `/dev/null/` as the destination probably won't work on Windows.

**Comment by pbrisbin** [comment]
Does setting it to [`NUL`](https://stackoverflow.com/questions/313111/is-there-a-dev-null-on-windows) work on windows?

I'm open to implementing something like `LOG_OUTPUT=null` as a way to disable logging entirely. If we find `NUL` works, it could just be a short-cut for doing the correct thing by platform.
